# Generated by Django 4.2.20 on 2025-04-05 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LengthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nominal_length', models.FloatField(help_text='Hesaplama için nominal uzunluk (cm)')),
                ('is_dynamic_length', models.BooleanField(default=False, help_text='Kısa parça mı?')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQualityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('total_area', models.FloatField(help_text='Tedarikçinin verdiği toplam m²')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_vat', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_price_with_vat', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pallets', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_pallets', to=settings.AUTH_USER_MODEL)),
                ('length_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lengthgroup')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='core.shipment')),
                ('supplier_quality_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplierqualitytype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pallets', to=settings.AUTH_USER_MODEL)),
                ('wood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.woodtype')),
            ],
        ),
    ]
