# Generated by Django 4.2.20 on 2025-04-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lengthgroup_supplierqualitytype_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='length_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lengthgroup', verbose_name='Uzunluk Grubu'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='core.shipment', verbose_name='Sevkiyat'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='supplier_quality_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplierqualitytype', verbose_name='Tedarikçi Kalitesi'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='total_area',
            field=models.FloatField(verbose_name='Toplam Alan (m²)'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat (₺ / m²)'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='KDV Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='wood_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.woodtype', verbose_name='Ahşap Türü'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.supplier', verbose_name='Tedarikçi'),
        ),
    ]
