# Generated by Django 4.2.20 on 2025-04-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_supplier_address_supplier_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
