# Generated by Django 4.2.20 on 2025-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodtype',
            name='wood_category',
            field=models.CharField(choices=[('dogal', 'Doğal'), ('yapay', 'Yapay')], default='dogal', max_length=10),
        ),
    ]
