# Generated by Django 4.2.20 on 2025-04-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_woodtype_wood_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='is_inspected',
            field=models.BooleanField(default=False, verbose_name='Denetim Durumu'),
        ),
    ]
