# Generated by Django 4.2.20 on 2025-04-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pallet_is_inspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='Bilgiler Girildi'),
        ),
    ]
